# Generated by Django 2.2.4 on 2019-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('info', models.CharField(max_length=500)),
                ('compony', models.CharField(max_length=50)),
            ],
        ),
    ]
